# Generated by Django 3.0.7 on 2020-06-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('userName', models.CharField(default='client8', max_length=10)),
                ('password', models.CharField(default='1762', max_length=10)),
                ('orderNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('returnUrl', models.SlugField(default='/')),
            ],
        ),
    ]
